### ISSUE TITLE
OpenHAB switches not discovered by HA

### ISSUE THREAD

**Issue by fba-ba** [kubawolanin/ha-openhab#19]
Hello, 

Thanks for developping this addon !
I cannot succeed to see my OpenHAB items in HA.
Here the items I'd like to see in HA ...
![image](https://user-images.githubusercontent.com/60670106/150492931-289d7822-c5ce-4065-aaa8-ab29fefabe03.png)

![image](https://user-images.githubusercontent.com/60670106/150493255-d5988cec-454b-405c-90f0-d6aab73991a9.png)

In the home-assistant log, I see...
2022-01-21 09:25:25 ERROR (MainThread) [homeassistant.components.switch] Error while setting up openhab platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 445, in _async_add_entity
    suggested_object_id = split_entity_id(entity.entity_id)[1]
IndexError: list index out of range

I successfully configured the OpenHAB integration ... using a token... and do not see anything special in the openhab logs...  

What am I doing wrong ? Please help ;-) ... 

François,

## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by kubawolanin** [comment]
Hey @fba-ba 
It might be helpful to provide `/rest/items` JSON from openHABs API as well.

Wild guess - Could you maybe remove French diacritics from Item's name and see if it helps?

**Comment by fba-ba** [comment]
I made a new trial by remove french diacritics... 

![image](https://user-images.githubusercontent.com/60670106/150506573-7073f9b3-4180-4c7f-865f-f38c1600e233.png)


![image](https://user-images.githubusercontent.com/60670106/150506434-3b698d56-c190-450a-b6cd-2b614b584935.png)


 curl -X 'GET' \
  'http://boule:8080/rest/items?recursive=false' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJraWQiOm51bGwsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJvcGVuaGFiIiwiYXVkIjoib3BlbmhhYiIsImV4cCI6MTY0Mjc2MzM1MSwianRpIjoiNnZJc0g3QWlhcVNPbXF3dnBfVTRhQSIsImlhdCI6MTY0Mjc1OTc1MSwibmJmIjoxNjQyNzU5NjMxLCJzdWIiOiJvcGVuaGFiIiwiY2xpZW50X2lkIjoiaHR0cDovL2JvdWxlOjgwODAiLCJzY29wZSI6ImFkbWluIiwicm9sZSI6WyJhZG1pbmlzdHJhdG9yIl19.I9AG1VNWi4NxEmVpx0h8PvpM3A8pFXOgif31XOp0eO7zZ_1yXbOprjLNHz3OMMJ58X5ViDveyXbgnZE1bswJBYgutx_CAn28B9btxmMm0rh4tT8zVwUJWJi_0GGqsBB2awMtK0TG0aUn81x8KaVvoOsrV7kQoVZFVgCUa4NQHh27yCadASuWVItDSuJEBVGJVNdqlrXUHBLah9q6_dd79hQvLVwluPEKGqshzO9iJLbTWpjEg7-_0nYUssa-nkYClnjaF54Hq1FYA2cmFQw7P6VYBcANrhSbBLzY047NxUDcp1t3ubJuaghd0nljn-lmbaTaAkQdd8T6QYhTfskgOQ'
[{"link":"http://boule:8080/rest/items/S1O3","state":"ON","stateDescription":{"readOnly":false,"options":[]},"editable":true,"type":"Switch","name":"S1O3","label":"Facade avant","category":"","tags":["Point"],"groupNames":[]}]

Same results in HomeAssistant :-( ...

**Comment by kubawolanin** [comment]
Could you please add the following lines to your `configuration.yaml` and paste the detailed logs?

```
logger:
  default: info
  logs:
    custom_components.openhab: debug
```

Looks like `entity.entity_id` is not properly set for the given item name.
Reference:
https://github.com/kubawolanin/ha-openhab/blob/master/custom_components/openhab/entity.py#L42

**Comment by fba-ba** [comment]
2022-01-21 17:57:30 INFO (MainThread) [custom_components.openhab]
-------------------------------------------------------------------
openHAB
Version: 0.0.1
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/kubawolanin/ha-openhab/issues
-------------------------------------------------------------------

2022-01-21 17:57:30 DEBUG (MainThread) [custom_components.openhab] Finished fetching openhab data in 0.146 seconds (success: True)
2022-01-21 17:57:30 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.openhab
2022-01-21 17:57:30 INFO (MainThread) [homeassistant.components.cover] Setting up cover.openhab
2022-01-21 17:57:30 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.openhab
2022-01-21 17:57:30 INFO (MainThread) [homeassistant.components.light] Setting up light.openhab
2022-01-21 17:57:30 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.openhab
2022-01-21 17:57:30 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.openhab
2022-01-21 17:57:30 INFO (MainThread) [homeassistant.components.switch] Setting up switch.openhab
2022-01-21 17:57:30 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform openhab
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 445, in _async_add_entity
    suggested_object_id = split_entity_id(entity.entity_id)[1]
IndexError: list index out of range
2022-01-21 17:57:30 ERROR (MainThread) [homeassistant.components.switch] Error while setting up openhab platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 445, in _async_add_entity
    suggested_object_id = split_entity_id(entity.entity_id)[1]
IndexError: list index out of range

**Comment by fba-ba** [comment]
Found a workaround using the IP address of openhab server instead of its hostname.
